name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort
      - name: Check style
        run: |
          black --check .
          flake8 .
          isort --check-only --diff .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run pytest
        run: |
          pytest \
            -v \
            --cov=custom_components.binary_matrix \
            -L --cov-report=xml \
            --cov-report=term-missing \
            tests

  validate:
    needs: [validate-hacs, validate-hassfest, style, tests]
    runs-on: ubuntu-latest
    steps:
      - name: All validations passed
        run: echo "All validations passed!"